apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: dsproject
objects:
  - kind: Project
    apiVersion: project.openshift.io/v1
    metadata:
      name: ${PROJECT_NAME}
      labels:
        kubernetes.io/metadata.name: ${PROJECT_NAME}
        maistra.io/member-of: istio-system
        modelmesh-enabled: 'false'
        opendatahub.io/dashboard: 'true'
      annotations:
        openshift.io/description: ''
        openshift.io/display-name: ${PROJECT_NAME}
    spec: {}
parameters:
  - name: PROJECT_NAME
    displayName: Project Name
    description: Project name
    required: true
    value: fraud-detection